#!/bin/bash

# USAGE:
compose=false   # -c    start many containers with docker compose
one=false       # -o    run one single docker container
stop=false      # -s    stop all docker containers
remove=false    # -r    remove all docker containers
build=false     # -b    build docker file
nodes="5"

# Parse
while getopts "c:osrb" opt; do
    case $opt in
        c)
            compose=true
            nodes=$OPTARG
            ;;
        o)
            one=true
            ;;
        s)
            stop=true
            ;;
        r)
            remove=true
            ;;
        b)
            build=true
            ;;
    esac
done

if [ "$stop" = true ]; then
    echo "##### Stopping all containers... #####"
    sudo docker stop $(sudo docker ps -aq)
fi

if [ "$remove" = true ]; then
    echo "##### Removing all containers... #####"
    sudo docker rm -f $(sudo docker ps -aq)
    sudo docker network rm d7024e_lab_kademlia_network
fi

if [ "$build" = true ]; then
    echo "##### Building image... #####"
    sudo docker build . -t kadlab
fi

if [ "$compose" = true ]; then
    echo "##### Starting $nodes containers... #####"
    sudo docker-compose --compatibility up -d --scale node="$nodes"
fi

if [ "$one" = true ]; then
    echo "##### Starting one containers... #####"
    sudo docker run kadlab
fi