#!/bin/bash

# USAGE:
compose=false   # -c    start many containers with docker compose
swarm=false     # -s    start many containers with docker swarm
one=false       # -o    run one single docker container
stop=false      # -t    stop all docker containers
remove=false    # -r    remove all docker containers
build=false     # -b    build docker file
kill=false      # -k    kill all
exec=false      # -e    start a terminal for given node ID
id="" 
nodes=""

# Parse
while getopts "c:s:otrbke:" opt; do
    case $opt in
        c)
            compose=true
            nodes=$OPTARG
            ;;
        s)
            swarm=true
            nodes=$OPTARG
            ;;
        o)
            one=true
            ;;
        t)
            stop=true
            ;;
        r)
            remove=true
            ;;
        b)
            build=true
            ;; 
        k)
            kill=true
            ;;
        e)
            exec=true
            id=$OPTARG
            ;;
    esac
done

if [ "$stop" = true ]; then
    echo "##### Stopping all containers... #####"
    sudo docker stop $(sudo docker ps -aq)
fi

if [ "$remove" = true ]; then
    echo "##### Removing all containers... #####"
    sudo docker rm -f $(sudo docker ps -aq)
fi

if [ "$kill" = true ]; then
    echo "##### Killing all containers... #####"
    sudo docker rm -f $(sudo docker ps -aq)
    echo "##### Killing service... #####"
    sudo docker service rm $(sudo docker service ls -q)
    echo "##### Killing service... #####"
    sudo docker network rm $(sudo docker network ls -q)
fi

if [ "$build" = true ]; then
    echo "##### Building image... #####"
    sudo docker build . -t kadlab
fi

if [ "$compose" = true ]; then
    echo "##### Starting $nodes containers... #####"
    sudo docker-compose --compatibility up -d --scale node="$nodes"
fi

if [ "$swarm" = true ]; then
    echo "##### Swarm init... #####"
    sudo docker swarm init
    echo "##### Starting service... #####"
    sudo docker stack deploy -c docker-compose.yml kadlab
    echo "##### Starting $nodes containers... #####"
    sudo docker service scale kadlab_node=$nodes
fi

if [ "$one" = true ]; then
    echo "##### Starting one containers... #####"
    sudo docker run kadlab
fi

if [ "$exec" = true ]; then
    echo "##### Starting terminal on node $id... #####"
    sudo docker exec -it $id sh
fi